### ISSUE TITLE
Does this module effect Wifi-6 ready phones?

### ISSUE THREAD

**Issue by BurhanBudak** [AndroPlus-org/magisk-module-wifi7#2]
I have a SD855+ with the WCN3990/WCN3991(Fast Connect 5900/6200) Wifi/BT chip. Before Wifi 6 was red on DeviceHWInfo but now its green. Obviously, my phone does not support Wi-Fi 7. I have an AX router that does not transmit Wi-Fi 6 signals, only 2.4 and 5 GHz on AX mode.

**Comment by AndroPlus-org** [comment]
Yes, I enabled Wi-Fi 6 support flag too so OS will think the device supports Wi-Fi 6 (regardless of the actual hardware support).
If the hardware does not support Wi-Fi 6, it will not be useable.

**Comment by BurhanBudak** [comment]
> Yes, I enabled Wi-Fi 6 support flag too so OS will think the device supports Wi-Fi 6 (regardless of the actual hardware support). If the hardware does not support Wi-Fi 6, it will not be usable.

Of course there are phone thart support only Wifi-4 and 5 separately with band steering, Wifi-AX that only transmits 2.4 and 5Ghz, Wifi-6E that is true 6Ghz and Wifi-7 that is band steering och 2,4,5,6 combined. My phones can recognize wifi-6 type but cant use the 6ghz signal from the router. I just wondered if it enables a secret setting for Wifi-6 **Ready** to be Wifi-6. Qualcomm just uses the same chip with some little change so there is some secret source for the chip. But Qualcomm is to blame, they are very inconsistent with their number naming scheme, they go back and release it with more options, my phones can support 5.0, 5.1 and 5.2 so its a mix of FC5900 and FC6200.

But thx for the answer, I will uninstall the module.

**Comment by BurhanBudak** [comment]
> Yes, I enabled Wi-Fi 6 support flag too so OS will think the device supports Wi-Fi 6 (regardless of the actual hardware support).
> If the hardware does not support Wi-Fi 6, it will not be useable.

Even if there is no support in the hardware, does this module give any kind of benefit or is this module more for users who live in a country where Wi-Fi 6 and 7 isn't certified for mainstream use?

**Comment by AndroPlus-org** [comment]
This module is for devices that are hardware-supported but disabled by software, such as China ROM devices.
If the hardware is not compatible, there is no benefit to using it.

**Comment by BurhanBudak** [comment]
> This module is for devices that are hardware-supported but disabled by software, such as China ROM devices.
> If the hardware is not compatible, there is no benefit to using it.

Thank you for the answer, but in theory is it possible to build a module that would also bump up the Bluetooth version or enable possible Bluetooth functions that wasn't shipped in stock?

**Comment by AndroPlus-org** [comment]
> > This module is for devices that are hardware-supported but disabled by software, such as China ROM devices.
> > If the hardware is not compatible, there is no benefit to using it.
> 
> Thank you for the answer, but in theory is it possible to build a module that would also bump up the Bluetooth version or enable possible Bluetooth functions that wasn't shipped in stock?

I think it needs modifying of Bluetooth library and difficult. It's possible if there's config / flag file like Wi-Fi, but there seems no such file in the system.

**Comment by BurhanBudak** [comment]
> I think it needs modifying of Bluetooth library and difficult. It's possible if there's config / flag file like Wi-Fi, but there seems no such file in the system.

Well Qualcomm bundels Wifi and BT as the same chip, plus the Bluetooth code is a module in Mainline. Bluetooth version has been inconsistent on Qualcomm.

**Comment by BurhanBudak** [comment]
@AndroPlus-org  off topic and I could see any issue tab on OpenEUICC, but did you update the module to the beta2 that Peter released?

**Comment by AndroPlus-org** [comment]
Not yet, I'll update it later when I have time.
